
export const exampleTracks = [
      {
        "id": 1,
        "artist": "Queen",
        "title": "Bohemian Rhapsody",
        "length": "3:44",
        "rating": 5,
        "thumbnailURL": "https://m.media-amazon.com/images/M/MV5BMjI4OTIwNDAxMF5BMl5BanBnXkFtZTgwOTkzOTAyODE@._V1_.jpg",
        "spotifyURL": "https://open.spotify.com/track/0v1XpBHnsbkCn7iJ9Ucr1l",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/bon-jovi/its-my-life-chords-951538",
        "lyricsURL": "https://www.azlyrics.com/lyrics/bonjovi/itsmylife.html"
      },
      {
        "id": 2,
        "artist": "Bon Jovi",
        "title": "It's My Life",
        "length": "3:46",
        "rating": 5,
        "thumbnailURL": "https://upload.wikimedia.org/wikipedia/en/9/96/BJ_Greatest.jpg",
        "spotifyURL": "https://open.spotify.com/track/0v1XpBHnsbkCn7iJ9Ucr1l",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/bon-jovi/its-my-life-chords-951538",
        "lyricsURL": "https://www.azlyrics.com/lyrics/bonjovi/itsmylife.html"
      },
      {
        "id": 3,
        "artist": "AC/DC",
        "title": "Back in Black",
        "length": "4:14",
        "rating": 5,
        "thumbnailURL": "https://i1.sndcdn.com/artworks-000084871237-w4wqxv-t500x500.jpg",
        "spotifyURL": "https://open.spotify.com/track/0v1XpBHnsbkCn7iJ9Ucr1l",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/ac-dc/back-in-black-chords-1264",
        "lyricsURL": "https://www.azlyrics.com/lyrics/acdc/backinblack.html"
      },
      {
        "id": 4,
        "artist": "Metallica",
        "title": "Enter Sandman",
        "length": "5:32",
        "rating": 4,
        "thumbnailURL": "https://www.revolvermag.com/sites/default/files/styles/original_image__844px_x_473px_/public/media/section-media/ridethelightning.jpg?itok=Fd0KtaS2&timestamp=1549044407",
        "spotifyURL": "https://open.spotify.com/track/0v1XpBHnsbkCn7iJ9Ucr1l",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/metallica/enter-sandman-chords-1274",
        "lyricsURL": "https://www.azlyrics.com/lyrics/metallica/entersandman.html"
      },
      {
        "id": 5,
        "artist": "Nirvana",
        "title": "Smells Like Teen Spirit",
        "length": "5:01",
        "rating": 5,
        "thumbnailURL": "https://m.media-amazon.com/images/I/51cm9yERxFL.jpg",
        "spotifyURL": "https://open.spotify.com/track/0v1XpBHnsbkCn7iJ9Ucr1l",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/nirvana/smells-like-teen-spirit-chords-1279",
        "lyricsURL": "https://www.azlyrics.com/lyrics/nirvana/smellsliketeenspirit.html"
      },
      {
        "id": 6,
        "artist": "Dua Lipa",
        "title": "Levitating",
        "length": "3:23",
        "rating": 4,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/47m9bXg9y8q939851nY07H",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/dua-lipa/levitating-chords-2645473",
        "lyricsURL": "https://www.azlyrics.com/lyrics/dualipa/levitating.html"
      },
      {
        "id": 7,
        "artist": "Ed Sheeran & Justin Bieber",
        "title": "I Don't Care",
        "length": "3:45",
        "rating": 3,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://www.youtube.com/watch?v=y83x7MgzWOA",
        "chordsURL": "https://www.youtube.com/watch?v=y83x7MgzWOA",
        "lyricsURL": "https://www.youtube.com/watch?v=y83x7MgzWOA"
      },
      {
        "id": 8,
        "artist": "The Weeknd",
        "title": "Blinding Lights",
        "length": "3:40",
        "rating": 3,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
        "chordsURL": "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
        "lyricsURL": "https://www.youtube.com/watch?v=4NRXx6U8ABQ"
      },
      {
        "id": 9,
        "artist": "Imagine Dragons",
        "title": "On Top of the World",
        "length": "3:12",
        "rating": 3,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://www.youtube.com/watch?v=w5tWYmIOWGk",
        "chordsURL": "https://www.youtube.com/watch?v=w5tWYmIOWGk",
        "lyricsURL": "https://www.youtube.com/watch?v=w5tWYmIOWGk"
      },
      {
        "id": 10,
        "artist": "LMFAO ft. Lauren Bennett & GoonRock",
        "title": "Party Rock Anthem",
        "length": "4:20",
        "rating": 2,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://www.youtube.com/watch?v=npWPZkbmWNM",
        "chordsURL": "https://www.youtube.com/watch?v=npWPZkbmWNM",
        "lyricsURL": "https://www.youtube.com/watch?v=npWPZkbmWNM"
      },
      {
        "id": 11,
        "artist": "John Williams",
        "title": "Star Wars: Main Theme",
        "length": "3:25",
        "rating": 5,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/john-williams/star-wars-main-theme-chords-17254",
        "lyricsURL": "https://www.azlyrics.com/lyrics/johnwilliams/starwarsmaintheme.html"
      },
      {
        "id": 12,
        "artist": "Nino Rota",
        "title": "The Godfather: Main Theme",
        "length": "3:10",
        "rating": 4,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/6F03d_8y8w4/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/nino-rota/the-godfather-main-theme-chords-17255",
        "lyricsURL": "https://www.azlyrics.com/lyrics/ninorota/thegodfathermaintheme.html"
      },
      {
        "id": 13,
        "artist": "John Williams",
        "title": "Schindler's List: Theme",
        "length": "3:20",
        "rating": 3,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/john-williams/schindlers-list-theme-chords-17256",
        "lyricsURL": "https://www.azlyrics.com/lyrics/johnwilliams/schindlerslisttheme.html"
      },
      {
        "id": 14,
        "artist": "Richard Strauss",
        "title": "2001: A Space Odyssey: Also sprach Zarathustra",
        "length": "9:20",
        "rating": 4,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/richard-strauss/2001-a-space-odyssey-also-sprach-zarathustra-chords-17257",
        "lyricsURL": "https://www.azlyrics.com/lyrics/richardstrauss/2001aspaceodysseyalsosprachzarathustra.html"
      },
      {
        "id": 15,
        "artist": "Maurice Jarre",
        "title": "Lawrence of Arabia: Main Theme",
        "length": "3:32",
        "rating": 2,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/maurice-jarre/lawrence-of-arabia-main-theme-chords-17258",
        "lyricsURL": "https://www.azlyrics.com/lyrics/mauricejarre/lawrenceofarabiamaintheme.html"
      },
      {
        "id": 16,
        "artist": "Harry Styles",
        "title": "As It Was",
        "length": "2:47",
        "rating": 4,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/4LRPiXqqa7FsONfc7a1cUL",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/harry-styles/as-it-was-chords-3696336",
        "lyricsURL": "https://www.azlyrics.com/lyrics/harrystyles/asitwas.html"
      },
      {
        "id": 17,
        "artist": "Glass Animals",
        "title": "Heat Waves",
        "length": "4:08",
        "rating": 3,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/1R8wAPMSEJQzZnq9vOOAYL",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/glass-animals/heat-waves-chords-2739273",
        "lyricsURL": "https://www.azlyrics.com/lyrics/glassanimals/heatwaves.html"
      },
      {
        "id": 18,
        "artist": "Elton John & Dua Lipa",
        "title": "Cold Heart (PNAU Remix)",
        "length": "3:22",
        "rating": 2,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/3uEA9UytJC6Usu1xSYvnzO",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/elton-john/cold-heart-pnau-remix-chords-3640122",
        "lyricsURL": "https://www.azlyrics.com/lyrics/eltonjohn/coldheartpnauremix.html"
      },
      {
        "id": 19,
        "artist": "The Weeknd",
        "title": "Out of Time",
        "length": "3:34",
        "rating": 1,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/5YMVRYlfYzQ5c2bAIAqXLi",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/the-weeknd/out-of-time-chords-3689923",
        "lyricsURL": "https://www.azlyrics.com/lyrics/theweeknd/outoftime.html"
      },
      {
        "id": 20,
        "artist": "Bad Bunny & Jhay Cortez",
        "title": "Me Porto Bonito",
        "length": "2:52",
        "rating": 3,
        "thumbnailURL": "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/classic-song-mixtape-album-cover-template-design-3ba3255137894fac49ae81b1346b289e_screen.jpg?ts=1635384548",
        "spotifyURL": "https://open.spotify.com/track/6Sq7يقةBgaYZ1qTHilYlXL",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/bad-bunny/me-porto-bonito-chords-3701231",
        "lyricsURL": "https://www.azlyrics.com/lyrics/badbunny/meportibonito.html"
      },
      {
        "id": 21,
        "artist": "Hiperkarma",
        "title": "Zöld Pardon",
        "length": "3:25",
        "rating": 5,
        "thumbnailURL": "https://www.a38.hu/storage/app/uploads/public/63c/6b6/5c4/thumb_158764_480_270_0_0_auto.jpg",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/hiperkarma/ebredj-fel-chords-17254",
        "lyricsURL": "https://www.azlyrics.com/lyrics/hiperkarma/ebredjfel.html"
      },
      {
        "id": 22,
        "artist": "Hiperkarma",
        "title": "Falon Túl",
        "length": "3:10",
        "rating": 5,
        "thumbnailURL": "https://www.a38.hu/storage/app/uploads/public/63c/6b6/5c4/thumb_158764_480_270_0_0_auto.jpg",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/hiperkarma/budai-hegyek-chords-17255",
        "lyricsURL": "https://www.azlyrics.com/lyrics/hiperkarma/budaihegyek.html"
      },
      {
        "id": 23,
        "artist": "Carson Coma",
        "title": "Legjobb verzió",
        "length": "3:20",
        "rating": 5,
        "thumbnailURL": "https://szentendre.hu/wp-content/uploads/2019/11/CarsonComa_4_komroczkidia.jpg",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/carsoncoma/a-te-hibad-chords-17256",
        "lyricsURL": "https://www.azlyrics.com/lyrics/carsoncoma/atehibad.html"
      },
      {
        "id": 24,
        "artist": "Carson Coma",
        "title": "Immunissá válunk",
        "length": "9:20",
        "rating": 5,
        "thumbnailURL": "https://szentendre.hu/wp-content/uploads/2019/11/CarsonComa_4_komroczkidia.jpg",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/carsoncoma/most-elsz-chords-17257",
        "lyricsURL": "https://www.azlyrics.com/lyrics/carsoncoma/mostelsz.html"
      },
      {
        "id": 25,
        "artist": "Carson Coma",
        "title": "Kék Hullám Kemping",
        "length": "3:32",
        "rating": 5,
        "thumbnailURL": "https://szentendre.hu/wp-content/uploads/2019/11/CarsonComa_4_komroczkidia.jpg",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/hiperkarma/maradj-velem-chords-17258",
        "lyricsURL": "https://www.azlyrics.com/lyrics/hiperkarma/maradjvelem.html"
      },
      {
        "id": 26,
        "artist": "Hiperkarma",
        "title": "Hiperkarma",
        "length": "3:32",
        "rating": 5,
        "thumbnailURL": "https://www.a38.hu/storage/app/uploads/public/63c/6b6/5c4/thumb_158764_480_270_0_0_auto.jpg",
        "spotifyURL": "https://open.spotify.com/track/45y3Qz003zQ/maxresdefault.jpg",
        "chordsURL": "https://tabs.ultimate-guitar.com/tab/hiperkarma/maradj-velem-chords-17258",
        "lyricsURL": "https://www.azlyrics.com/lyrics/hiperkarma/maradjvelem.html"
      },
];
